"use client";

export function Footer() {
  return (
    <footer className="bg-[#002395] text-white py-12">
      <div className="swiss-container">
        <div className="flex flex-col md:flex-row justify-between items-center gap-6">
          <div>
            <p className="font-semibold text-lg">API Documentation</p>
            <p className="text-white/70 text-sm mt-1">Version 4.0 • Complete Technical Reference</p>
          </div>
          
          <div className="text-center md:text-right">
            <p className="text-white/70 text-sm">
              For API key requests or technical assistance, please contact your account manager.
            </p>
          </div>
        </div>
        
        <div className="mt-8 pt-6 border-t border-white/20 text-center">
          <p className="text-white/50 text-xs">
            Generated by AS.
          </p>
        </div>
      </div>
    </footer>
  );
}
